[project]
name = "anki-card-maker-companion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "genanki>=0.13.1",
    "ipykernel>=6.29.5",
    "pydantic-ai>=0.2.14",
    "streamlit>=1.45.1",
]
